Not searching for unused variables given on the command line.
[36m--[0m The C compiler identification is GNU 9.4.0
[36m--[0m The CXX compiler identification is GNU 9.4.0
[36m--[0m Check for working C compiler: /usr/bin/cc
[36m--[0m Check for working C compiler: /usr/bin/cc -- works
[36m--[0m Detecting C compiler ABI info
[36m--[0m Detecting C compiler ABI info - done
[36m--[0m Detecting C compile features
[36m--[0m Detecting C compile features - done
[36m--[0m Check for working CXX compiler: /usr/bin/c++
[36m--[0m Check for working CXX compiler: /usr/bin/c++ -- works
[36m--[0m Detecting CXX compiler ABI info
[36m--[0m Detecting CXX compiler ABI info - done
[36m--[0m Detecting CXX compile features
[36m--[0m Detecting CXX compile features - done
[36m--[0m Using CATKIN_DEVEL_PREFIX: /home/sunyu/work/Tactile-Sevice-Robot-Mobility-Assistance/pinocchio_sim_ws/devel/.private/tactile_compliance
[36m--[0m Using CMAKE_PREFIX_PATH: /home/sunyu/work/Tactile-Sevice-Robot-Mobility-Assistance/pinocchio_sim_ws/devel;/opt/ros/noetic
[36m--[0m This workspace overlays: /home/sunyu/work/Tactile-Sevice-Robot-Mobility-Assistance/pinocchio_sim_ws/devel;/opt/ros/noetic
[36m--[0m Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3")
[36m--[0m Using PYTHON_EXECUTABLE: /usr/bin/python3
[36m--[0m Using Debian Python package layout
[36m--[0m Found PY_em: /usr/lib/python3/dist-packages/em.py
[36m--[0m Using empy: /usr/lib/python3/dist-packages/em.py
[36m--[0m Using CATKIN_ENABLE_TESTING: ON
[36m--[0m Call enable_testing()
[36m--[0m Using CATKIN_TEST_RESULTS_DIR: /home/sunyu/work/Tactile-Sevice-Robot-Mobility-Assistance/pinocchio_sim_ws/build/tactile_compliance/test_results
[36m--[0m Forcing gtest/gmock from source, though one was otherwise available.
[36m--[0m Found gtest sources under '/usr/src/googletest': gtests will be built
[36m--[0m Found gmock sources under '/usr/src/googletest': gmock will be built
[36m--[0m Found PythonInterp: /usr/bin/python3 (found version "3.8.10")
[36m--[0m Found Threads: TRUE
[36m--[0m Using Python nosetests: /usr/bin/nosetests3
[36m--[0m catkin 0.8.10
[36m--[0m BUILD_SHARED_LIBS is on
[36m--[0m Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
[36m--[0m pinocchio FOUND. pinocchio at /opt/ros/noetic/lib/libpinocchio.so
[36m--[0m boost_filesystem FOUND. boost_filesystem at /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
[36m--[0m boost_serialization FOUND. boost_serialization at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
[36m--[0m boost_system FOUND. boost_system at /usr/lib/x86_64-linux-gnu/libboost_system.so
[36m--[0m Found Boost: /usr/local/include (found version "1.71.0") found components: filesystem serialization system
[36m--[0m eigenpy FOUND. eigenpy at /opt/ros/noetic/lib/x86_64-linux-gnu/libeigenpy.so
[36m--[0m Checking for NumPy
[36m--[0m   NUMPY_INCLUDE_DIRS=/usr/local/lib/python3.8/dist-packages/numpy/core/include
[36m--[0m   NUMPY_VERSION=1.24.0
[36m--[0m Found Python3: /usr/bin/python3 (found version "3.8.10") found components: Interpreter NumPy Development
[36m--[0m PythonLibraryDirs: /usr/lib/x86_64-linux-gnu
[36m--[0m PythonLibVersionString: 3.8.10
[36m--[0m Python site lib: lib/python3.8/dist-packages
[36m--[0m Python include dirs: /usr/include/python3.8
[36m--[0m Checking for NumPy
[36m--[0m   NUMPY_INCLUDE_DIRS=/usr/local/lib/python3.8/dist-packages/numpy/core/include
[36m--[0m   NUMPY_VERSION=1.24.0
[36m--[0m NumPy include dir: /usr/local/lib/python3.8/dist-packages/numpy/core/include
[31m[1mCMake Error[0m at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: python38) (found version "1.71.0")
[36mCall Stack (most recent call first):[0m
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  /opt/ros/noetic/share/eigenpy/cmake/boost.cmake:144 (find_package)
  /opt/ros/noetic/share/eigenpy/cmake/eigenpyConfig.cmake:149 (SEARCH_FOR_BOOST_PYTHON)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/ros/noetic/share/cmake/pinocchio/pinocchioConfig.cmake:160 (find_dependency)
  CMakeLists.txt:32 (find_package)


[36m--[0m Configuring incomplete, errors occurred!
See also "/home/sunyu/work/Tactile-Sevice-Robot-Mobility-Assistance/pinocchio_sim_ws/build/tactile_compliance/CMakeFiles/CMakeOutput.log".
See also "/home/sunyu/work/Tactile-Sevice-Robot-Mobility-Assistance/pinocchio_sim_ws/build/tactile_compliance/CMakeFiles/CMakeError.log".
